### PR TITLE
Fix/issue33

### PR DESCRIPTION
**Pull request by nickp60**
This addresses issue #33 

Would anyone with a dev environment already set up be willing to clone and run the test suite? 

- [X] 🐛 &nbsp; Bug fix
- [X] 🚀 &nbsp; New feature
- [ ] 🔧 &nbsp; Code refactor
- [ ] ⚠️ &nbsp; Breaking change that would cause existing functionality to change
- [ ] 📘 &nbsp; I have updated the documentation accordingly
- [ ] ✅ &nbsp; I have added tests to cover my changes

### CODE REVIEW

**Comment by juanesarango** [comment]
Great. I can help you set up your dev environment. You basically just need to install the deps and tests deps inside a virtual environment and then run tests with docker.

This is how I do it. You can use conda or any python env util:
```bash
export MY_ENV=isabl_cli_env
mkvirtualenv -p python3 $MY_ENV
workon $MY_ENV
pip install -r requirements.txt

sh tests/test-with-compose.sh
```

Where do you get stuck?

**Comment by juanesarango** [comment]
Screen Shot 2023-02-03 at 5 00 31 PM

**Comment by nickp60** [comment]
I tried both the instructions you gave and the instructions in the contributing guide and I get the same (different) test errors:
Screen Shot 2023-02-06 at 10 02 11 AM

Based on your screenshot, I tried to fix the error, but I can't reproduce it yet.

**Comment by juanesarango** [comment]
Good process. You get the test suite to run with most of the tests successfully. 
Let's try troubleshoot the chmod error

**Comment by nickp60** [comment]
reopening from branch rather than for so CI runs

**Pull request closed without merging**
