### PR TITLE
Create ci-cd.yaml

### PR DESCRIPTION
**Pull request by nickp60**
This adds a github action configured to use [trusted publishing](https://pypi.org/manage/account/publishing/)

- [ ] 🐛 &nbsp; Bug fix
- [X] 🚀 &nbsp; New feature
- [ ] 🔧 &nbsp; Code refactor
- [ ] ⚠️ &nbsp; Breaking change that would cause existing functionality to change
- [ ] 📘 &nbsp; I have updated the documentation accordingly
- [ ] ✅ &nbsp; I have added tests to cover my changes

### CODE REVIEW

**Comment by juanesarango** [comment]
Hi @nickp60 can you elaborate on how this github action works? It builds always, but only publishes when a new release is done? And where are the org and credentials defined of pypi?

**Comment by nickp60** [comment]
Hi @juanesarango , missed your message, sorry! Yes, I tried to lift the bulk of the logic from what you have set up for travis.  This is geared to use [trusted publishing](https://docs.pypi.org/trusted-publishers/creating-a-project-through-oidc/) which lets you avoid manually setting secrets and tokens.  I can't test this fully [until this issue is resolved](https://github.com/pypi/support/issues/2784), as `isabl_cli` is registered with pypi but it seems no one knows who registered it.

And yes -- it builds on pushes and pull requests right now, but can be configured however you want.

**Comment by juanesarango** [comment]
Hi @nickp60 let's merge this and test how it goes! I see pypi hasn't respond about the support issue you created.

Thanks for your contribution!

**Review by juanesarango — COMMENTED** [review]
Thanks for your help!

**Pull request merged**
